// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXVKu-OghqKvSdwcEh9r2KgS_BC4mzXsU',
    appId: '1:1024384454422:web:2da80b1e1d78b9b9110a37',
    messagingSenderId: '1024384454422',
    projectId: 'taxibookingapp-grp52',
    authDomain: 'taxibookingapp-grp52.firebaseapp.com',
    storageBucket: 'taxibookingapp-grp52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBId-FbSVtq1HuKIQme4JJbuyQ3lu3xyDw',
    appId: '1:1024384454422:android:5834778949287085110a37',
    messagingSenderId: '1024384454422',
    projectId: 'taxibookingapp-grp52',
    storageBucket: 'taxibookingapp-grp52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAraltvGt2iHBS84Zu10HC1DStETEPoBxc',
    appId: '1:1024384454422:ios:e4b4356a5eded792110a37',
    messagingSenderId: '1024384454422',
    projectId: 'taxibookingapp-grp52',
    storageBucket: 'taxibookingapp-grp52.appspot.com',
    androidClientId: '1024384454422-su4p8kd3qq05k1u2ianbrk41uv9njsb2.apps.googleusercontent.com',
    iosClientId: '1024384454422-mgfk2oqiufi06di9cdgarqa31eel0vpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiBookingApp',
  );
}
